sudo: false
language: android
jdk:
  - oraclejdk8

android:
    components:
      - build-tools-23.0.1
      - android-23
      - extra

install:
  - ./gradlew assembleRelease --info

before_script:
  - chmod +x gradlew

script:
    - ./gradlew check --info

